baseURL = 'https://blog.butubb.cn/'
languageCode = 'zh-cn'
title = '日志'
theme = 'PaperMod'
defaultContentLanguage = 'zh-cn'



[params]
  defaultTheme = "auto"
  # 内联表必须写在一行内
  homeInfoParams = { Title = "你好！我是butubb，安徽人，现工作居住在苏州。", Content = "喜欢互联网冲浪🏄‍♂️，折腾机器💻，看电影🎥，编程🧑‍💻，听音乐🎶等" }


[taxonomies]
  tag = "tags"
  series = "series"
  category = "categories"

[[menu.main]]
  name = "首页"
  url = "/"
  weight = 1

[[menu.main]]
  name = "归档"
  url = "/archives"
  weight = 2

[[menu.main]]
  name = "标签"
  url = "/tags"
  weight = 3
